import "./globals.css";
import type { Metadata } from "next";
import { Josefin_Sans } from "next/font/google";

const josefin_Sans = Josefin_Sans({
  weight: ["300", "400", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon-32x32.png",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={josefin_Sans.className + " font-normal"}>{children}</body>
    </html>
  );
}
